#!/usr/bin/env bash
# Launch one orchestrator session for one Linear Project in its own worktree.
#
# Usage: launch.sh <project-slug> [--name <dir/branch name>] [--branch <name>]
#                  [--base-ref <ref>] [--no-up] [--no-cmux] [--dry-run]
#
# Stack-agnostic. The project supplies an isolation hook through its
# .claude/orchestrate.md `## Isolation` slot:
#   hook: <path>          script implementing the protocol below (optional)
#   base_ref: <ref>       default origin/main
#   worktrees: <dir>      parent dir for generic worktrees, default ../ (ignored when hook set)
#
# Hook protocol (cwd = the project checkout launch.sh was run from):
#   <hook> add <branch> <base_ref>   create the worktree; LAST stdout line = its absolute path
#   <hook> env                       cwd = worktree; stdout = KEY=VALUE lines for the session env
#   <hook> up                        cwd = worktree; start services / first build (skipped by --no-up)
# Without a hook: git worktree add -b <branch> <worktrees>/<repo>-<name> <base_ref>, no env, no up.
#
# Then: writes ~/.local/state/orchestrate/<repo>-<name>.env, and either opens a cmux
# workspace running claude there (`/orchestrate <slug>` as the first prompt, telemetry
# resource attributes tagged with linear.project=<slug>) or prints the command.
set -euo pipefail

slug=""; name=""; branch=""; base_ref=""; do_up=1; use_cmux=1; dry=0
while [ $# -gt 0 ]; do
  case "$1" in
    --name) name="${2:?}"; shift 2 ;;
    --branch) branch="${2:?}"; shift 2 ;;
    --base-ref) base_ref="${2:?}"; shift 2 ;;
    --no-up) do_up=0; shift ;;
    --no-cmux) use_cmux=0; shift ;;
    --dry-run) dry=1; shift ;;
    -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
    -*) printf 'unknown option: %s\n' "$1" >&2; exit 2 ;;
    *) [ -z "$slug" ] && slug="$1" || { printf 'unexpected argument: %s\n' "$1" >&2; exit 2; }; shift ;;
  esac
done
[ -n "$slug" ] || { printf 'usage: launch.sh <project-slug> [options]\n' >&2; exit 2; }

root="$(git rev-parse --show-toplevel 2>/dev/null)" || { printf 'run from inside the project checkout\n' >&2; exit 2; }
cd "$root"
repo="$(basename "$(git worktree list --porcelain | head -1 | sed 's/^worktree //')")"
[ "$repo" = main ] && repo="$(basename "$(dirname "$(git worktree list --porcelain | head -1 | sed 's/^worktree //')")")"
name="${name:-$slug}"
branch="${branch:-orchestrate/$name}"

# Profile keys from `## Isolation`.
profile=".claude/orchestrate.md"
# `- key: \`value\` trailing prose` or `key: value` — the first backticked or bare token after the colon.
key() { [ -f "$profile" ] && awk -v h="## Isolation" '$0==h{on=1;next} /^## /{on=0} on' "$profile" | sed -nE "s/^[-* ]*$1:[[:space:]]*(\`([^\`]+)\`|([^[:space:]]+)).*$/\2\3/p" | head -1 || true; }
hook="$(key hook)"; [ -z "$base_ref" ] && base_ref="$(key base_ref)"; base_ref="${base_ref:-origin/main}"
wt_parent="$(key worktrees)"; wt_parent="${wt_parent:-..}"
case "$hook" in ""|/*) ;; *) hook="$root/$hook" ;; esac   # absolute: it is invoked from inside the worktree too
[ -n "$hook" ] && [ ! -x "$hook" ] && { printf 'isolation hook %s is not executable\n' "$hook" >&2; exit 2; }

# Linear project exists? fail-open (CLI or network may be absent).
if command -v linear >/dev/null 2>&1; then
  linear project view "$slug" >/dev/null 2>&1 || printf 'warning: `linear project view %s` failed; check the slug\n' "$slug" >&2
fi

state="${XDG_STATE_HOME:-$HOME/.local/state}/orchestrate"; mkdir -p "$state"
envfile="$state/$repo-$name.env"

say() { printf '%s\n' "$*"; }
say "project:   $slug"
say "repo:      $repo   branch: $branch   base: $base_ref"
say "hook:      ${hook:-<none: generic git worktree>}"

# 1. worktree
if git worktree list --porcelain | grep -q "^branch refs/heads/$branch\$"; then
  wt="$(git worktree list --porcelain | awk -v b="refs/heads/$branch" '/^worktree /{w=$2} $0=="branch "b{print w}')"
  say "worktree:  $wt (exists, reused)"
else
  if [ "$dry" -eq 1 ]; then
    wt="$(cd "$wt_parent" 2>/dev/null && pwd)/$repo-$name"; [ -n "$hook" ] && wt="<hook add $branch $base_ref>"
    say "worktree:  $wt (would create)"
  elif [ -n "$hook" ]; then
    wt="$("$hook" add "$branch" "$base_ref" | tee /dev/stderr | tail -1)"
    [ -d "$wt" ] || { printf 'hook add did not print an existing directory as its last line (got: %s)\n' "$wt" >&2; exit 1; }
  else
    wt="$(cd "$wt_parent" && pwd)/$repo-$name"
    git fetch -q origin 2>/dev/null || true
    git worktree add -b "$branch" "$wt" "$base_ref"
  fi
  [ "$dry" -eq 1 ] || say "worktree:  $wt (created)"
fi

# 2. session env
otel_base="$(jq -r '.env.OTEL_RESOURCE_ATTRIBUTES // empty' "$HOME/.claude/settings.json" 2>/dev/null || true)"
otel="${otel_base:+$otel_base,}linear.project=$slug,git.branch=$branch"
{
  printf '# generated by orchestrate/launch.sh %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'ORCHESTRATE_PROJECT=%s\nORCHESTRATE_BRANCH=%s\n' "$slug" "$branch"
  if [ -n "$hook" ] && [ "$dry" -eq 0 ]; then (cd "$wt" && "$hook" env); fi
} > "$envfile"
say "env:       $envfile"
[ "$dry" -eq 0 ] && grep -v '^#' "$envfile" | sed 's/^/           /'

# 3. services / first build
if [ -n "$hook" ] && [ "$do_up" -eq 1 ] && [ "$dry" -eq 0 ]; then
  say "up:        running $hook up in $wt"
  ( cd "$wt" && set -a && . "$envfile" && set +a && "$hook" up )
fi

# 4. the session
settings="$(jq -cn --arg o "$otel" '{env:{OTEL_RESOURCE_ATTRIBUTES:$o}}' 2>/dev/null || printf '{"env":{"OTEL_RESOURCE_ATTRIBUTES":"%s"}}' "$otel")"
cmd="cd '$wt' && set -a && . '$envfile' && set +a && claude --settings '$settings' '/orchestrate $slug'"
say "command:   $cmd"
[ "$dry" -eq 1 ] && { say "dry run: nothing created"; exit 0; }

cmux="${CMUX_BIN:-/Applications/cmux.app/Contents/Resources/bin/cmux}"
if [ "$use_cmux" -eq 1 ] && [ -x "$cmux" ] && "$cmux" ping >/dev/null 2>&1; then
  "$cmux" new-workspace --name "orch: $name" --cwd "$wt" --command "$cmd" --focus false >/dev/null
  say "cmux:      workspace 'orch: $name' opened (not focused)"
else
  command -v pbcopy >/dev/null 2>&1 && printf '%s' "$cmd" | pbcopy && say "cmux:      unavailable; command copied to clipboard" || say "cmux:      unavailable; run the command above"
fi
